# Generated by Django 5.2.17 on 2026-10-03 04:34

import accounts.uuidv7
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.UUIDField(default=accounts.uuidv7.uuidv7, editable=False, primary_key=True, serialize=False)),
                ('auth_path', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'authentication',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginCredential',
            fields=[
                ('id', models.UUIDField(default=accounts.uuidv7.uuidv7, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_column='user_id', max_length=10)),
                ('username', models.CharField(max_length=70, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('enable_flag', models.BooleanField(default=True)),
                ('biometric_info', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'login_credential',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=accounts.uuidv7.uuidv7, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('gender', models.CharField(max_length=2)),
                ('birth_date', models.DateField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
