"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# DJANGO_ENV: 'dev' | 'test' | 'prod' — controls which DB name default is used
# and which .env.<env> file gets loaded on top of the base .env
DJANGO_ENV = os.environ.get('DJANGO_ENV', 'dev')
if DJANGO_ENV not in ('dev', 'test', 'prod'):
    raise RuntimeError("DJANGO_ENV must be one of: 'dev', 'test', 'prod'")

# Load base env first, then environment-specific override (if present)
load_dotenv(BASE_DIR / '.env', override=False)
_env_file = BASE_DIR / f'.env.{DJANGO_ENV}'
if _env_file.exists():
    load_dotenv(_env_file, override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Require explicit SECRET_KEY in test/prod to avoid accidental insecure defaults
if DJANGO_ENV == 'dev':
    SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'unsafe-dev-secret-key-change-in-prod')
else:
    SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
    if not SECRET_KEY:
        raise RuntimeError(f'DJANGO_SECRET_KEY is required when DJANGO_ENV={DJANGO_ENV}')

# SECURITY WARNING: don't run with debug turned on in production!
# Default: dev=True, test=False, prod=False
_debug_default = 'True' if DJANGO_ENV == 'dev' else 'False'
DEBUG = os.environ.get('DJANGO_DEBUG', _debug_default).lower() == 'true'

# ALLOWED_HOSTS: comma-separated list from env, or localhost defaults for dev
_allowed_hosts_env = os.environ.get('DJANGO_ALLOWED_HOSTS')
if _allowed_hosts_env:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1'] if DJANGO_ENV == 'dev' else []

if not ALLOWED_HOSTS:
    raise RuntimeError(
        f'DJANGO_ALLOWED_HOSTS env var is required when DJANGO_ENV={DJANGO_ENV}. '
        'Example: "yourdomain.com,www.yourdomain.com"'
    )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Default DB names follow convention: tttapp_dev | tttapp_test | tttapp_prod
# Override by setting DB_NAME explicitly in your .env or .env.<env>
_DB_NAME_DEFAULT = f'tttapp_{DJANGO_ENV}'

DB_NAME = os.environ.get('DB_NAME', _DB_NAME_DEFAULT)
DB_USER = os.environ.get('DB_USER')
DB_PASSWORD = os.environ.get('DB_PASSWORD')
DB_HOST = os.environ.get('DB_HOST', '127.0.0.1')
DB_PORT = os.environ.get('DB_PORT', '5432')

if not DB_USER or not DB_PASSWORD:
    raise RuntimeError(
        'Missing DB credentials. Set DB_USER and DB_PASSWORD in your .env file. '
        f'DB_NAME will default to "{_DB_NAME_DEFAULT}" based on DJANGO_ENV={DJANGO_ENV} '
        'unless you override it explicitly.'
    )

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.authentication.SignedTokenAuthentication',
    ],
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
